### ISSUE TITLE
How can I handle Callbacks in case of message failed validation?

### ISSUE THREAD

**Issue by aph5nt** [NServiceBusExtensions/NServiceBus.Validation#102]
Hi, I'm trying to figure out how can I send back a response with an error message?

My use case is quite simple: I send a SayHello message and I expect to receive Greet message back.
I case of failure this code will timeout, what I don't like too much.

`var greet = await endpointInstance.Request<Greet>(new SayHello{ Name = "" })
                .ConfigureAwait(false);`

If it would be possible to add validation results into the SayHello message headers or something? Then I could intercept the validation results in the message handler and send back the proper response.

**Comment by SimonCropp** [comment]
https://github.com/NServiceBusExtensions/Home/blob/master/readme.md

**Comment by SimonCropp** [comment]
@aph5nt you need to [be a patron to be using this library](https://github.com/NServiceBusExtensions/Home/blob/master/readme.md#licensingpatron-faq)
